force-app/main/default/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Candidate ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Junction__c/Junction__c.object-meta.xml
<CustomObject>
    <label>Junction</label>
    <nameField>
        <label>Junction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Junctions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Junction__c/fields/position_candidate_association__c.field-meta.xml
<CustomField>
    <fullName>position_candidate_association__c</fullName>
    <label>Candidate</label>
    <referenceTo>Candidate__c</referenceTo>
    <relationshipLabel>Junctions</relationshipLabel>
    <relationshipName>Junctions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Junction__c/fields/position_candidateassociation__c.field-meta.xml
<CustomField>
    <fullName>position_candidateassociation__c</fullName>
    <label>Position</label>
    <referenceTo>Positions__c</referenceTo>
    <relationshipLabel>Junctions</relationshipLabel>
    <relationshipName>Junctions</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Positions__c/Positions__c.object-meta.xml
<CustomObject>
    <label>Position</label>
    <nameField>
        <label>Positions Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/apexq2.cls
public class apexq2{
 public Map<string,list<string>> mymap;
    list<Junction__c> l1;
    list<string> l2=new list<string>();
    list<string> l3=new list<string>();
    public apexq2(){
            
         l1=[SELECT position_candidateassociation__r.Name, position_candidate_association__r.First_Name__c FROM Junction__c];
    
         mymap = new Map<string,list<string>>();
    
        
    
        for (Junction__c J :l1)
        {
           if(mymap.containsKey(J.position_candidateassociation__r.Name)) {
               l2=new list<string>();
            l2.addAll(mymap.get(J.position_candidateassociation__r.Name));
            l2.add(j.position_candidate_association__r.First_Name__c);
           mymap.put(J.position_candidateassociation__r.Name,  l2);
           }
           else{
              
           mymap.put(J.position_candidateassociation__r.Name,new List<String>{j.position_candidate_association__r.First_Name__c});
           
     
            }   
     }
    }
 public list<String> checkvalue(string name1){
    
    
        if(mymap.containsKey(name1)){
            return mymap.get(name1);
        }
        else{
            return null;
        }

}
}