force-app/main/default/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Candidate ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate__c/fields/gender__c.field-meta.xml
<CustomField>
    <fullName>gender__c</fullName>
    <label>gender</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>male</fullName>
            </value>
            <value>
                <fullName>female</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/apexq3.cls
public class apexq3{

set<String > myset;
public apexq3(){
    
    
    set<Candidate__c> myset = new set<Candidate__c>([SELECT email__c,gender__c,mobile__c FROM Candidate__c]);
   // List<Candidate__c> mylist = new List<Candidate__c>([SELECT email__c,gender__c,mobile__c FROM Candidate__c])
  //  for(integer i=0;i<mylist.size();i++){
   //     myset.add(mylist[i]);
//}
   list<Candidate__c>mylist=new list<Candidate__c>([SELECT email__c,gender__c,mobile__c FROM Candidate__c]) ;
   
    
    
    
    System.debug('2,,,,,,,'+myset.size());

}

}